dist: xenial
language: node_js
node_js:
  - 10
services:
  - docker
before_install:
  - sudo apt-get install -y libgconf-2-4
  - git clone https://github.com/dready92/d10-fixtures.git
  - docker-compose up -d
  - ss -ltpn
script:
  - $(npm bin)/cypress run
after_script:
  - docker-compose logs d10
