dist: xenial
language: node_js
node_js:
  - 10
services:
  - docker
before_install:
  - sudo apt-get install -y lame vorbis-tools flac faad2 graphicsmagick
  - npm install
  - docker-compose up
  - sleep 30
script:
  - $(npm bin)/cypress run

