dist: xenial
language: node_js
node_js:
  - 10
services:
  - docker
before_install:
  - env
  - sudo apt-get install -y libgconf-2-4
#  - docker-compose up -d
#  - ls -l
#  - ls -l node_modules/
# install:
#  - npm install
script:
  - $(npm bin)/cypress run

