dist: xenial
language: node_js
node_js:
  - 10
services:
  - docker
before_install:
  - env
  - sudo apt-get install -y libgconf-2-4
  - git clone https://github.com/dready92/d10-fixtures.git
  - docker-compose up -d
script:
  - $(npm bin)/cypress run

