exports.couch = {
	d10: {dsn: "http://localhost:5984/",database:"d10-test"},
	auth: {dsn: "http://localhost:5984/",database:"auth-test"},
	track: {dsn: "http://localhost:5984/",database:"track-test"}
};

// templates path
exports.templates = {
	node: "../views/"
};

// cookie name
exports.cookieName = "goodcacke";

// cookie time to live ( in miliseconds )
exports.cookieTtl = 1000*60*60*24*15;

// results per page
exports.rpp = 30;

exports.audio = {
	tmpdir: "../audio/tmp",
	dir: "../audio/files"
};

exports.cmds = {
	file: "/usr/bin/file",
	file_options: "-bi",
	lame: "/usr/bin/lame",
	lame_opts:  ["--mp3input","--quiet","--decode","-","-"],
	oggenc: "/usr/bin/oggenc",
	oggenc_opts: ["--quiet","-o"],
	ogginfo: "/usr/bin/ogginfo",
	utrac: "/usr/local/bin/utrac",
	taginfo: "/usr/local/bin/taginfo",
	vorbiscomment: "/usr/bin/vorbiscomment"
	
}


exports.javascript = {
	includes : [
		"modernizr-1.5.min.js",
		"jquery.sprintf.js",
		"jquery.tools.min.js",
		"jquery.csstransform.js",
		"jquery.ovlay.js",
		"jquery.includes.js",
		"dnd.js",
		"utils.js",
		"track.js",
		"player.js",
		"menumanager.js",
		"httpbroker.js",
		"playlist.js",
		"paginer.js",
		"plm.js",
		"my.js",
		"upload.js",
		"library.js",
		"welcome.js",
		"results.js",
		"user.js",
		"osd.js",
		"localcache.js",
		"bgtask.js"
	]
};

exports.genres = [
'Blues',
'Classic Rock',
'Country',
'Dance',
'Disco',
'Funk',
'Grunge',
'Hip-Hop',
'Jazz',
'Metal',
'New Age',
'Oldies',
'Other',
'Pop',
'R&B',
'Rap',
'Reggae',
'Rock',
'Techno',
'Industrial',
'Alternative',
'Ska',
'Death Metal',
'Pranks',
'Soundtrack',
'Euro-Techno',
'Ambient',
'Trip-Hop',
'Vocal',
'Jazz+Funk',
'Fusion',
'Trance',
'Classical',
'Instrumental',
'Acid',
'House',
'Game',
'Sound Clip',
'Gospel',
'Noise',
'Alternative Rock',
'Bass',
'Soul',
'Punk',
'Space',
'Meditative',
'Instrumental Pop',
'Instrumental Rock',
'Ethnic',
'Gothic',
'Darkwave',
'Techno-Industrial',
'Electronic',
'Pop-Folk',
'Eurodance',
'Dream',
'Southern Rock',
'Comedy',
'Cult',
 'Gangsta',
'Top 40',
'Christian Rap',
'Pop/Funk',
'Jungle',
'Native US',
'Cabaret',
'New Wave',
'Psychedelic',
'Rave',
'Showtunes',
'Trailer',
 'Lo-Fi',
'Tribal',
'Acid Punk',
 'Acid Jazz',
 'Polka',
 'Retro',
'Musical',
'Rock & Roll',
'Hard Rock',
'Folk',
'Folk-Rock',
'National Folk',
'Swing',
'Fast Fusion',
'Bebob',
'Latin',
'Revival',
'Celtic',
'Bluegrass',
'Avantgarde',
'Gothic Rock',
'Progressive Rock',
'Psychedelic Rock',
'Symphonic Rock',
'Slow Rock',
'Big Band',
'Chorus',
'Easy Listening',
'Acoustic',
'Humour',
'Speech',
'Chanson',
'Opera',
'Chamber Music',
'Sonata',
'Symphony',
'Booty Bass',
'Primus',
'Porn Groove',
'Satire',
'Slow Jam',
'Club',
'Tango',
'Samba',
'Folklore',
'Ballad',
'Power Ballad',
'Rhytmic Soul',
'Freestyle',
'Duet',
'Punk Rock',
'Drum Solo',
'Acapella',
'Euro-House',
'Dance Hall',
'Goa',
'Drum & Bass',
'Club-House',
'Hardcore',
'Terror',
'Indie',
'BritPop',
'Negerpunk',
'Polsk Punk',
'Beat',
'Christian Gangsta',
'Heavy Metal',
'Black Metal',
'Crossover',
'Contemporary C',
'Christian Rock',
'Merengue',
'Salsa',
'Thrash Metal',
'Anime',
'JPop',
'SynthPop',
'Dub'
];